
fullnameOverride: "filebeat123"
filebeatConfig:
  filebeat.yml: |
    filebeat.autodiscover:
      providers:
        - type: kubernetes
          templates:
            - config:
                - type: container
                  paths:
                    - /var/log/containers/*.log
                  processors:
                    - add_kubernetes_metadata: ~
    output.console:
      pretty: true      
    logging.level: info
